# Generated by Django 4.1.1 on 2023-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
